### ISSUE TITLE
Cannot use CDN

### ISSUE THREAD

**Issue by chladnefazole** [josias-r/boarding.js#17]
Hello, I am trying to include this library as a CDN on my website, but I get error: Uncaught SyntaxError: export declarations may only appear at top level of a module

Problem is with this line, which is at the end of the file:
````
export {
  it as Boarding
};
````

CDN: view-source:https://unpkg.com/boarding.js@3.5.2/dist/main.js

**Comment by chladnefazole** [comment]
Fixed, changed type of import to "module"

**Comment by josias-r** [comment]
Thank you for the report, and I'll update the docs to include that information. And since browsersupport for modules is green for the major browsers, I won't build another dist at the moment.

But in case anyone ever stumbles accross this issue abd `<script type="module">` is not an option for them, feel free to request a different build :)
