### ISSUE TITLE
Handling click on element inside description

### ISSUE THREAD

**Issue by netojso** [josias-r/boarding.js#25]
```
this.driverRecord.highlight({
        element: findElement as HTMLElement,
        popover: {
          description: `<button id="bt" onclick="(()=>alert('hi'))()">Gravar</button>`,
          title: 'Gravação',
        },
      });
```

I can't receive a alert from this button, but the close button works.

**Comment by josias-r** [comment]
@netojso Probably a cleaner way to attach eventlisteners to your HTML description, is to add it in JS to the ID/Class with `document.getElementById("bt").addEventListener(...)`.

Just make sure this event is called in a hook AFTER the popup has rendered, otherwise `document.getElementById` would not find the button yet.
